<h1><?php echo $this->titulo?></h1>
<?php
$form = $this->form;
$form->prepare();


$form->setAttributes(array(
    'action' => $this->url.'/application/index/index',
    'method' => 'post'
));
// Get the form label plugin
$formLabel = $this->plugin('formLabel');

// Render the opening tag
echo $this->form()->openTag($form);
?>
<?php
if(!empty($this->id))
{
    ?>
    <p style="color: green;">El registro se ingreso correctamente</p>
    <?php
}
?>
<div class="form_element">
<?php
    $name = $form->get('nombre');
    echo $formLabel->openTag().$name->getOption('label')." ";
    
    //echo $this->formElementErrors($name);
    echo $formLabel->closeTag();
    echo $this->formInput($name);
?>
</div>
<div class="form_element">

<?php
    $correo = $form->get('correo');
    echo $formLabel->openTag().$correo->getOption('label')." ";
    
    //echo $this->formElementErrors($name);
    echo $formLabel->closeTag();
    echo $this->formInput($correo);
?>
</div>
<?php echo $this->formElement($form->get('send')) ?>
<?php echo $this->form()->closeTag() ?>