<h1><?php echo $this->titulo?></h1>
<?php
$form = $this->form;
$form->prepare();


$form->setAttributes(array(
    'action' => $this->url.'/docentes/',
    'method' => 'post'
));
// Get the form label plugin
$formLabel = $this->plugin('formLabel');

// Render the opening tag
echo $this->form()->openTag($form);
?>
<?php
if(!empty($this->id))
{
    ?>
    <p style="color: green;">El registro se ingreso correctamente</p>
    <?php
}
?>
    
<div class="form_element">
<?php
    $cedula = $form->get('cedula');   
    echo $formLabel->openTag().$cedula->getOption('label')." ";
    
    //echo $this->formElementErrors($name);
    echo $formLabel->closeTag();
    echo $this->formInput($cedula);
?>
</div>
<div class="form_element">
<?php
    $nombres = $form->get('nombres');   
    echo $formLabel->openTag().$nombres->getOption('label')." ";
    
    //echo $this->formElementErrors($name);
    echo $formLabel->closeTag();
    echo $this->formInput($nombres);
?>
</div>
<div class="form_element">

<?php
    $apellidos = $form->get('apellidos');
    echo $formLabel->openTag().$apellidos->getOption('label')." ";
    
    //echo $this->formElementErrors($name);
    echo $formLabel->closeTag();
    echo $this->formInput($apellidos);
?>
</div>
    
<div class="form_element">

<?php
    $codigo = $form->get('codigo');
    echo $formLabel->openTag().$codigo->getOption('label')." ";
    
    //echo $this->formElementErrors($name);
    echo $formLabel->closeTag();
    echo $this->formInput($codigo);
?>
</div>
    
<div class="form_element">

<div class="form_element">
    <?php
    $facultad = $form->get('facultad');
    echo $formLabel->openTag() . $facultad->getLabel();
    echo $formLabel->closeTag();
    echo "<br/>";
    echo $this->formRadio($facultad);
    echo $this->formElementErrors($facultad);
    ?>
</div>
    <br />
    
<div class="form_element">

<div class="form_element">
    <?php
    $unidadacademica = $form->get('unidadacademica');
    echo $formLabel->openTag() . $unidadacademica->getLabel();
    echo $formLabel->closeTag();
    echo "<br/>";
    echo $this->formRadio($unidadacademica);
    echo $this->formElementErrors($unidadacademica);
    ?>
</div>
    <br />
    
<div class="form_element">

<?php
    $semestre = $form->get('semestre');
    echo $formLabel->openTag().$semestre->getOption('label')." ";
    
    //echo $this->formElementErrors($name);
    echo $formLabel->closeTag();
    echo $this->formInput($semestre);
?>
</div>
    
<div class="form_element">

<?php
    $formacion = $form->get('formacion');
    echo $formLabel->openTag().$formacion->getOption('label')." ";
    
    //echo $this->formElementErrors($name);
    echo $formLabel->closeTag();
    echo $this->formInput($formacion);
?>
</div>
    
<div class="form_element">

<?php
    $direccion = $form->get('direccion');
    echo $formLabel->openTag().$direccion->getOption('label')." ";
    
    //echo $this->formElementErrors($name);
    echo $formLabel->closeTag();
    echo $this->formInput($direccion);
?>
</div>
    
<div class="form_element">

<?php
    $telefono = $form->get('telefono');
    echo $formLabel->openTag().$telefono->getOption('label')." ";
    
    //echo $this->formElementErrors($name);
    echo $formLabel->closeTag();
    echo $this->formInput($telefono);
?>
</div>
    
<div class="form_element">

<?php
    $correo = $form->get('correo');
    echo $formLabel->openTag().$correo->getOption('label')." ";
    
    //echo $this->formElementErrors($name);
    echo $formLabel->closeTag();
    echo $this->formInput($correo);
?>
</div>
<?php echo $this->formElement($form->get('send')) ?>
<?php echo $this->form()->closeTag() ?>

