<h1><?php echo $this->titulo?></h1>
<?php
$form = $this->form;
$form->prepare();


$form->setAttributes(array(
    'action' => $this->url.'/docentes/index/',
    'method' => 'post'
));
// Get the form label plugin
$formLabel = $this->plugin('formLabel');

// Render the opening tag
echo $this->form()->openTag($form);
?>
<?php
if(!empty($this->id))
{
    ?>
    <p style="color: green;">El registro se ingreso correctamente</p>
    <?php
}
?>
    
<div class="form_element">
<?php
    $name = $form->get('cedula');   
    echo $formLabel->openTag().$name->getOption('label')." ";
    
    //echo $this->formElementErrors($name);
    echo $formLabel->closeTag();
    echo $this->formInput($name);
?>
</div>
<div class="form_element">
<?php
    $name = $form->get('nombre');   
    echo $formLabel->openTag().$name->getOption('label')." ";
    
    //echo $this->formElementErrors($name);
    echo $formLabel->closeTag();
    echo $this->formInput($name);
?>
</div>
<div class="form_element">

<?php
    $codigo = $form->get('apellido');
    echo $formLabel->openTag().$codigo->getOption('label')." ";
    
    //echo $this->formElementErrors($name);
    echo $formLabel->closeTag();
    echo $this->formInput($codigo);
?>
</div>
    
<div class="form_element">

<?php
    $codigo = $form->get('codigo');
    echo $formLabel->openTag().$codigo->getOption('label')." ";
    
    //echo $this->formElementErrors($name);
    echo $formLabel->closeTag();
    echo $this->formInput($codigo);
?>
</div>
    
<div class="form_element">

<?php
    $codigo = $form->get('facultad');
    echo $formLabel->openTag().$codigo->getOption('label')." ";
    
    //echo $this->formElementErrors($name);
    echo $formLabel->closeTag();
    echo $this->formInput($codigo);
?>
</div>
    
<div class="form_element">

<?php
    $codigo = $form->get('unidadacademica');
    echo $formLabel->openTag().$codigo->getOption('label')." ";
    
    //echo $this->formElementErrors($name);
    echo $formLabel->closeTag();
    echo $this->formInput($codigo);
?>
</div>
    
<div class="form_element">

<?php
    $codigo = $form->get('semestreaño');
    echo $formLabel->openTag().$codigo->getOption('label')." ";
    
    //echo $this->formElementErrors($name);
    echo $formLabel->closeTag();
    echo $this->formInput($codigo);
?>
</div>
    
<div class="form_element">

<?php
    $codigo = $form->get('formacion');
    echo $formLabel->openTag().$codigo->getOption('label')." ";
    
    //echo $this->formElementErrors($name);
    echo $formLabel->closeTag();
    echo $this->formInput($codigo);
?>
</div>
    
<div class="form_element">

<?php
    $codigo = $form->get('direccion');
    echo $formLabel->openTag().$codigo->getOption('label')." ";
    
    //echo $this->formElementErrors($name);
    echo $formLabel->closeTag();
    echo $this->formInput($codigo);
?>
</div>
    
<div class="form_element">

<?php
    $codigo = $form->get('telefono');
    echo $formLabel->openTag().$codigo->getOption('label')." ";
    
    //echo $this->formElementErrors($name);
    echo $formLabel->closeTag();
    echo $this->formInput($codigo);
?>
</div>
    
<div class="form_element">

<?php
    $codigo = $form->get('correo');
    echo $formLabel->openTag().$codigo->getOption('label')." ";
    
    //echo $this->formElementErrors($name);
    echo $formLabel->closeTag();
    echo $this->formInput($codigo);
?>
</div>
<?php echo $this->formElement($form->get('send')) ?>
<?php echo $this->form()->closeTag() ?>

