<h1><?php echo $this->titulo?></h1>
<?php
$form = $this->form;
$form->prepare();


$form->setAttributes(array(
    'action' => $this->url.'/actividades/index/crear',
    'method' => 'post'
));
// Get the form label plugin
$formLabel = $this->plugin('formLabel');

// Render the opening tag
echo $this->form()->openTag($form);
?>
<?php
if(!empty($this->id))
{
    ?>
    <p style="color: green;">El registro se ingreso correctamente</p>
    <?php
}
?>
    
<div class="form_element">
<?php
    $codactividades = $form->get('codactividades');   
    echo $formLabel->openTag().$codactividades->getOption('label')." ";
    
    //echo $this->formElementErrors($name);
    echo $formLabel->closeTag();
    echo $this->formInput($codactividades);
?>
</div>

<div class="form_element">
<?php
    $nombre = $form->get('nombre');   
    echo $formLabel->openTag().$nombre->getOption('label')." ";
    
    //echo $this->formElementErrors($name);
    echo $formLabel->closeTag();
    echo $this->formInput($nombre);
?>
</div>
    
<div class="form_element">
<?php
    $descripcion = $form->get('descripcion');   
    echo $formLabel->openTag().$descripcion->getOption('label')." ";
    
    //echo $this->formElementErrors($name);
    echo $formLabel->closeTag();
    echo $this->formInput($descripcion);
?>
</div>

<div class="form_element">
<?php
    $responsable = $form->get('responsable');   
    echo $formLabel->openTag().$responsable->getOption('label')." ";
    
    //echo $this->formElementErrors($name);
    echo $formLabel->closeTag();
    echo $this->formInput($responsable);
?>
</div>

<div class="form_element">
<?php
    $valoracion = $form->get('valoracion');   
    echo $formLabel->openTag().$valoracion->getOption('label')." ";
    
    //echo $this->formElementErrors($name);
    echo $formLabel->closeTag();
    echo $this->formInput($valoracion);
?>
</div> 
    
<div class="form_element">
<?php
    $coddocente = $form->get('coddocente');   
    echo $formLabel->openTag().$coddocente->getOption('label')." ";
    
    //echo $this->formElementErrors($name);
    echo $formLabel->closeTag();
    echo $this->formSelect($coddocente);
?>
</div>  

<div class="form_element">
<?php
    $codtipomodalidad = $form->get('codtipo');   
    echo $formLabel->openTag().$codtipomodalidad->getOption('label')." ";
    
    //echo $this->formElementErrors($name);
    echo $formLabel->closeTag();
    echo $this->formSelect($codtipomodalidad);
?>
</div>      

<?php echo $this->formElement($form->get('send')) ?>
<?php echo $this->form()->closeTag() ?>

